#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
gate6_preamble.py — Dynamic preamble generator & inserter.

Scans LaTeX snippets for features and emits a minimal preamble with only the
packages required. Optionally inserts \\input{preamble.tex} into main.tex
immediately after \\documentclass{...} if not already present.

Usage:
  python scripts/gate6_preamble.py \
    --snippets-dir build/snippets \
    --out build/preamble.tex \
    --main-tex build/main.tex \
    --insert 1
"""

from __future__ import annotations
import argparse
import json
import re
from pathlib import Path
from typing import Dict, Set

HERE = Path(__file__).resolve().parent
PROJECT_ROOT = HERE.parent

FEATURES: Dict[str, re.Pattern] = {
    # math & symbols
    "amsmath": re.compile(r"\\begin\{(?:align\*?|equation\*?|gather\*?|multline\*?)\}|\\\(|\\\[|\\frac\{"),
    "amssymb": re.compile(r"\\mathbb\{|\\mathcal\{|\\mathfrak\{|\\mathscr\{"),
    # figures/graphics
    "graphicx": re.compile(r"\\includegraphics(?:\[[^\]]*\])?\{[^}]+\}"),
    # tables
    "booktabs": re.compile(r"\\(toprule|midrule|bottomrule)"),
    "tabular": re.compile(r"\\begin\{(?:tabular\*?|tabularx|longtable)\}"),
    # color & hyperlinks
    "xcolor": re.compile(r"\\textcolor\{|\\color\{|\\definecolor\{"),
    "hyperref": re.compile(r"\\href\{|\\url\{"),
}

ALLOWLIST_ORDER = [
    # keep a stable order for deterministic diffs
    "amsmath",
    "amssymb",
    "graphicx",
    "booktabs",
    "tabular",
    "xcolor",
    "hyperref",
]

PACKAGE_LINES = {
    "amsmath": r"\usepackage{amsmath}",
    "amssymb": r"\usepackage{amssymb}",
    "graphicx": r"\usepackage{graphicx}",
    "booktabs": r"\usepackage{booktabs}",
    "tabular": r"% (tabular core is built-in; consider array/tabularx/longtable as needed)",
    "xcolor": r"\usepackage{xcolor}",
    "hyperref": r"\usepackage{hyperref}",
}

ROUTE_FEATURE_HINTS = {
    "figure": {"graphicx"},
    "figure_placeholder": {"graphicx"},
    "table": {"booktabs"},
    "math": {"amsmath"},
}


def scan_features(snippets_dir: Path) -> Set[str]:
    feats: Set[str] = set()
    if not snippets_dir.exists():
        return feats
    for tex in snippets_dir.rglob("*.tex"):
        try:
            text = tex.read_text(encoding="utf-8", errors="replace")
        except Exception:
            continue
        for name, patt in FEATURES.items():
            if patt.search(text):
                feats.add(name)
    # Merge metadata-derived hints
    for meta_path in snippets_dir.rglob("*.meta.json"):
        try:
            data = json.loads(meta_path.read_text(encoding="utf-8"))
        except Exception:
            continue
        for cap in data.get("capabilities", []) or []:
            if cap in PACKAGE_LINES:
                feats.add(cap)
        route_meta = data.get("route_metadata") or {}
        specialist = (route_meta.get("specialist") or "").strip()
        if specialist in ROUTE_FEATURE_HINTS:
            feats.update(ROUTE_FEATURE_HINTS[specialist])
        route_reason = (data.get("route") or "").strip()
        for key, extra in ROUTE_FEATURE_HINTS.items():
            if key and key in route_reason:
                feats.update(extra)
    return feats


def write_preamble(out_path: Path, features: Set[str]) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "% Auto-generated by gate6_preamble.py",
        "% This file is intentionally a fragment to be \\input{} after \\documentclass",
    ]
    for name in ALLOWLIST_ORDER:
        if name in features:
            lines.append(PACKAGE_LINES[name])
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def ensure_input_in_main(main_tex: Path, preamble_rel: str = "preamble.tex") -> bool:
    """
    Insert \\input{preamble.tex} immediately after \\documentclass if missing.
    Returns True if modified, False otherwise.
    """
    if not main_tex.exists():
        return False
    text = main_tex.read_text(encoding="utf-8", errors="replace")
    if "\\input{preamble.tex}" in text or "\\input{"+preamble_rel+"}" in text:
        return False

    lines = text.splitlines()
    for i, line in enumerate(lines):
        if line.strip().startswith("\\documentclass"):
            lines.insert(i + 1, f"\\input{{{preamble_rel}}}")
            main_tex.write_text("\n".join(lines) + "\n", encoding="utf-8")
            return True
    # If no documentclass found, prepend as last resort
    main_tex.write_text(f"\\input{{{preamble_rel}}}\n" + text, encoding="utf-8")
    return True


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--snippets-dir", type=Path, required=True)
    ap.add_argument("--out", type=Path, required=True, help="Output preamble path (e.g., build/preamble.tex)")
    ap.add_argument("--main-tex", type=Path, default=None, help="Optional: inject \\input{preamble.tex} into this file")
    ap.add_argument("--insert", type=int, default=1, help="If 1 and --main-tex set, insert \\input{} when missing")
    args = ap.parse_args()

    feats = scan_features(args.snippets_dir)
    write_preamble(args.out, feats)

    modified = False
    if args.main_tex and args.insert:
        # Compute relative path from main.tex to preamble (usually just 'preamble.tex')
        preamble_rel = Path(args.out.name)
        modified = ensure_input_in_main(args.main_tex, preamble_rel=str(preamble_rel))

    print(f"[gate6] features={sorted(feats)}; wrote={args.out}; injected={modified}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
