# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: sudo apt-get update; sudo apt-get install -y pdftohtml qpdf just

    - name: Free up space
      run: just free_up_space

    - name: Install venv
      run: just install_venv

    - name: Lint with black
      run: just check_format

    - name: Start service
      run: just start_detached

    - name: Check API ready
      uses: emilioschepis/wait-for-endpoint@v1.0.3
      with:
        url: http://localhost:5060
        method: GET
        expected-status: 200
        timeout: 120000
        interval: 500

    - name: Test with unittest
      run: just test
